[package]
name = "bridge-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
bridge-core = { path = "../bridge-core" }
clap = { version = "4.4", features = ["derive"] }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = "0.3"
