[package]
name = "bridge-core"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
log.workspace = true
anyhow.workspace = true
hex.workspace = true
bcs.workspace = true
reqwest.workspace = true
sui-json-rpc-types.workspace = true
sui-keys.workspace = true
shared-crypto.workspace = true
sui-config.workspace = true
sui-transaction-builder.workspace = true

# Sui SDK dependencies
sui-sdk.workspace = true
sui-types.workspace = true
move-core-types.workspace = true

[dev-dependencies]
mockall.workspace = true
mockito.workspace = true
tokio-test.workspace = true