[package]
name = "sui_bridge"
version = "0.0.1"
edition = "2024.beta"

[addresses]
sui_bridge = "0x0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "main" } 